Dev-FE-2/toy-project2-team1

.gitignore, package-lock.json, package.json, src/firebaseConfig.ts, src/hooks/useFirebaseCustomLogin.ts, src/hooks/useFirestoreUserRegistration.ts, src/layout/Layout.tsx, src/layout/header/Header.tsx, src/layout/nav/Footer.tsx, src/layout/nav/Navbar.tsx, src/layout/nav/Sidebar.tsx, src/pages/Calendar/Calendar.tsx, src/pages/CorrectionRequest/CorrectionRequest.tsx, src/pages/Home/Home.tsx, src/pages/Login/Login.tsx, src/pages/Profile/Profile.tsx, src/pages/Register/Register.tsx, src/pages/SalaryDetails/SalaryDetails.tsx, src/routes/router.tsx, src/styles/GlobalStyles.tsx, tsconfig.app.json, vite.config.ts
**[파이어베이스 초기세팅 및 파이어스토어 적용]**
- 파이어베이스 초기세팅 및 파이어스토어 적용
- .env파일 추가 및 파이어베이스 api 키관련 속성들 추가
- gitignore에 .env 추가
- watch 스크립트 tsconfig.app.json 바라보게 변경
- noEmit 옵션 : false로 변경
- 라우팅 구조 레이아웃 추가로 변경
- 글로벌 스타일 적용
- 회원가입, 로그인 테스트용 코드 작성
- 헤더, 메인 영역, 사이드바, 푸터 영역으로 변경
현재는 테스트용으로 회원가입과 로그인의 경우 userId, password 속성으로 로그인하게 되어있으며,
파이어베이스 로그인 인증 부분을 커스텀으로 작성하였는데, 만약 파이어베이스에서 제공하는 로그인 인증으로
사용하게 된다면 userId가 email속성으로 변경되어 사용자 아이디는 무조건 이메일 속성으로 사용하게 변경됩니다.
관련하여 레퍼런스 찾아보겠습니다.
=> [⚙️ Setting] 파이어베이스 초기세팅 및 파이어스토어 적용

src/hooks/useFirestoreUserRegistration.ts, src/pages/Register/Register.tsx
**[인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경]**
- 인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경
=> [🔧 Fix] 인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경

src/hooks/useFirestoreUserRegistration.ts, src/pages/Register/Register.tsx
**[[🔧 Fix] 인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경]**
- 인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경
=> [🔧 Fix] 인터페이스 타입 관련 오류 수정 및 회원가입 커스텀 훅 코드 변경 (#8)

src/hooks/useFirestoreUserRegistration.ts, src/pages/Register/Register.styles.ts, src/pages/Register/Register.tsx, src/pages/index.ts
**[스타일 컴포넌트 임포트 오류로 인한 디렉토리 삭제 및 재설정]**
- 스타일 컴포넌트 임포트 오류로 인한 디렉토리 삭제 및 재설정
=> [🔧 Fix] 스타일 컴포넌트 임포트 오류로 인한 디렉토리 삭제 및 재설정

.eslintrc.cjs, tsconfig.app.json
**[TypeScript any 타입 허용 설정 추가]**
- TypeScript any 타입 허용 설정 추가
=> [⚙️ Setting] TypeScript any 타입 허용 설정 추가

package-lock.json, package.json, src/components/checkbox/CheckboxGroup.tsx, src/components/schedule-management/clalendar/Calendar.tsx, src/components/schedule-management/schedule-card/UserScheduleCard.tsx, src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.tsx, src/components/schedule-management/schedule-modal/ScheduleModal.tsx, src/redux/actions/scheduleActions.ts, src/utils/filterSchedulesByDate.ts, supabaseConfig.ts
**[작업 내용을 간략히 적어주세요]**
- 파이어베이스에서 Supabase로 마이그레이션
1. Create (추가)
Firebase와 Supabase 동시 추가 처리
```javascript
export const addScheduleToFirestore = (
userId: string | undefined,
schedules: TSchedule[],
): AppThunk<Promise<TScheduleApiResponse<void>>> => {
return async (dispatch) => {
if (!userId) {
return {
success: false,
message: '사용자 ID가 없습니다.',
};
}
dispatch(setisLoading(true));
dispatch(setisLoading(true));
try {
const userDocRef = doc(db, 'schedules', userId);
const userDoc = await getDoc(userDocRef);
if (!userDoc.exists()) {
if (!userDoc.exists()) {
// 사용자 문서가 없으면 새로 생성
await setDoc(userDocRef, {
schedules: schedules.map((schedule) => ({
...schedule,
created_at: Timestamp.now(),
})),
});
} else {
// 기존 스케줄 배열에 새 스케줄 추가
const existingSchedules = …
```
=> [✨ Feature] 파이어베이스에서 Supabase로 마이그레이션

src/components/PaginatedTable/PaginatedTable.tsx, src/components/salaryselect/salarySelect.tsx, src/components/table/table.tsx, src/pages/salary-user/SalaryDetails.tsx
selected박스를 기준으로한 데이터 필터입니다
selected박스를 기준으로한 데이터 필터입니다
develop 브랜치에서 새로 파서 다시 진행하였습니다....
=> [✨ Feature] 년,월 기준으로 데이터 필터 ✨ Feature

src/components/index.ts, src/components/schedule-management/clalendar/admin-calendar/AdminCalendar.tsx, src/components/schedule-management/clalendar/user-calendar/Calendar.tsx, src/pages/schedule-management/ScheduleManagement.tsx, src/redux/actionTypes.ts, src/redux/actions/scheduleActions.ts, src/redux/reducers/scheduleReducer.ts
관리자 전체 직원 일정 관리 보여주기
관리자 전체 직원 일정 관리 보여주기
=> [✨ Feature] 관리자 전체 직원 일정 관리 보여주기

src/pages/login/Login.tsx
**[작업 내용을 간략히 적어주세요]**
- 로그인 페이지 로그인폼 삭제로 인한 재설정
=> [🔧 Fix] 로그인 페이지 로그인폼 삭제로 인한 재설정

src/components/schedule-management/calendar/Calender.tsx
[🔄 Refactor] 관리자 일정 목록에서 카테고리 -> 직원 이름 변경
- [🔄 Refactor] 관리자 일정 목록에서 카테고리 -> 직원 이름 변경
- [🔄 Refactor] 관리자 일정 목록에서 카테고리 -> 직원 이름 변경
=> [🔄 Refactor] 관리자 일정 목록에서 카테고리 -> 직원 이름 변경

src/components/nav/Navbar.styles.ts, src/components/nav/Navbar.tsx, src/components/nav/NavbarItem.tsx
navbar에서 해당 url에 따라 menu 하이트라이트 주기
- navbar에서 해당 url에 따라 menu 하이트라이트 주기
- navbar에서 해당 url에 따라 menu 하이트라이트 주기
=> [✨ Feature] navbar에서 해당 url에 따라 menu 하이트라이트 주기

src/components/PaginatedTable/DetailModal/MainDetailModal.tsx, src/components/home/MainLayout.tsx, src/components/nav/Navbar.styles.ts, src/components/nav/Navbar.tsx, src/components/nav/NavbarItem.tsx, src/components/schedule-management/calendar/Calender.tsx, src/components/schedule-management/schedule-modal/ScheduleModal.styles.ts
- navbar 디자인토큰 사용
- MainLayout 불필요 console.log 제거
- navbar 디자인토큰 사용
- MainLayout 불필요 console.log 제거
close #130
=> [🔄 Refactor] navbar 디자인토큰 사용

src/components/PaginatedTable/DetailModal/MainDetailModal.tsx, src/components/PaginatedTable/DetailModal/detailModal.style.ts, src/components/PaginatedTable/DetailModal/detailModal.tsx, src/components/PaginatedTable/EditModal/hook/useSupabaseData.ts, src/components/home/MainLayout.tsx
item.tax_deduction 데이터 추가
실지급액을 연산으로 수정
급여내역서 스타일 조정
item.tax_deduction 데이터 추가
실지급액을 연산으로 수정
급여내역서 스타일 조정
item.tax_deduction 데이터 추가
실지급액을 연산으로 수정
급여내역서 스타일 조정
=> [🔄 Refactor]세금공제 데이터 누락 수정 

src/components/PaginatedTable/CheckingResult/checkingResult.styled.ts, src/components/PaginatedTable/CheckingResult/checkingResult.tsx, src/components/PaginatedTable/DetailModal/detailModal.style.ts, src/components/PaginatedTable/DetailModal/detailModal.tsx, src/components/PaginatedTable/PaginatedTable.tsx, src/pages/application details/ApplicationDeatils.styled.ts, src/pages/application details/ApplicationDetails.tsx, src/routes/router.tsx
정정신청내역확인 추가입니다.
정정신청내역확인 추가입니다.
=> [✨ Feature] 정정신청확인 추가 

src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.styles.ts, src/components/schedule-management/schedule-card/admin-schedule-card/AdminScheduleCard.tsx, src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.styles.ts, src/components/schedule-management/schedule-list/admin-schedule-list/AdminScheduleList.tsx, src/components/schedule-management/schedule-list/user-schedule-list/UserScheduleList.styles.ts, src/components/schedule-management/schedule-modal/ScheduleModal.tsx, src/pages/schedule-management/ScheduleManagement.tsx, src/redux/actions/scheduleActions.ts, src/types/schedule.ts
관리자 수정, 삭제 폼 로직 수정 (userId 분기처리, 선택 안했을때 오류 표시)
관리자 스케줄 리스트, 카드 스타일 수정
관리자 수정, 삭제 폼 로직 수정 (userId 분기처리, 선택 안했을때 오류 표시)
관리자 스케줄 리스트, 카드 스타일 수정
close #135
=> [✨ Feature] 관리자 스케줄 리스트 근무시간추가, css 추가

src/components/PaginatedTable/DetailModal/detailModal.tsx, src/components/PaginatedTable/EditModal/editModal.tsx, src/components/PaginatedTable/PaginatedTable.tsx, src/hooks/useSalaryUserData.ts, src/pages/application details/ApplicationDetails.tsx, src/pages/salary-management/SalaryManagement.tsx
급여내역 카테고리를 추가하였습니다.
정정 신청에따른 급여내역 카테고리를 추가하였습니다.
=> [🔄 Refactor] 급여내역 카테고리 조정

README.md
[📚 Docs] README.md 작성하기
[📚 Docs] README.md 작성하기
[📚 Docs] README.md 작성하기
=> [📚 Docs] README.md 작성하기

src/components/home/MainLayout.styles.ts, src/components/home/MainLayout.tsx, src/hooks/useWorkingHours.ts
**[작업 내용을 간략히 적어주세요]**
- 근무 시간 영역 주차 계산 수정 및 쿼리 수정
=> [🔧 Fix] 근무 시간 영역 주차 계산 수정 및 쿼리 수정

src/components/home/MainLayout.styles.ts, src/components/home/MainLayout.tsx, src/components/home/WorkingHours.tsx, src/components/schedule-management/schedule-modal/ScheduleModal.tsx, src/utils/filteredRepeatSchedules.ts, src/utils/generateRepeatingSchedules.ts
관리자 근무시간 영역 없애기
반복 스케줄 계산 로직 수정
관리자 근무시간 영역 없애기
반복 스케줄 계산 로직 수정
관리자 근무시간 영역 없애기
반복 스케줄 계산 로직 수정
close #147
=> [🔧 Fix] 발표 준비하며 이상한 부분 수정

src/components/schedule-management/calendar/Calendar.styles.ts, src/components/schedule-management/calendar/Calender.tsx
[✨ Feature] 사용자 일정관리에서 현재 날짜를 기준으로 이전 날짜들은 비활성화 구현
[✨ Feature] 사용자 일정관리에서 현재 날짜를 기준으로 이전 날짜들은 비활성화 구현
[✨ Feature] 사용자 일정관리에서 현재 날짜를 기준으로 이전 날짜들은 비활성화 구현
=> [✨ Feature] 사용자 일정관리에서 현재 날짜를 기준으로 이전 날짜들은 비활성화 구현

src/components/schedule-management/calendar/Calender.tsx, src/hooks/useRegister.ts, src/pages/profile/Profile.tsx
**[작업 내용을 간략히 적어주세요]**
- 회원관련 기능 슈퍼베이스 users 테이블로 변경
=> [✨ Feature] 회원관련 기능 슈퍼베이스 users 테이블로 변경
